FROM python:3.11-slim

WORKDIR /app

COPY requirements-docker.txt .
RUN pip --no-cache-dir install --upgrade pip setuptools wheel && pip --no-cache-dir install -r requirements-docker.txt

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV MODEL_DIR=/app/output/model
ENV OUTPUT_DIR=/app/output

COPY src/ src/
COPY api/ api/
COPY output/model/ /app/output/model/

EXPOSE 8080

ENTRYPOINT ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080"]
